apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: cloudage
      image: tabrezid54/cloudjob
      imagePullPolicy: Always
      ports:
      - containerPort: 80
